---
- name: Create main directory
  ansible.builtin.file:
    path: "{{ lighttpd_document_root }}"
    state: directory
    owner: "{{ lighttpd_user }}"
    group: "{{ lighttpd_group }}"
    mode: '0755'

- name: Deploy config file lighttpd.conf
  ansible.builtin.template:
    src: lighttpd.conf.j2
    dest: "{{ lighttpd_conf_path }}"
    mode: '0644'
  notify: restart lighttpd
