---
- name: Установка EPEL репозитория (для RedHat)
  ansible.builtin.package:
    name: "{{ lighttpd_epel_package }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Установка пакета Lighttpd
  ansible.builtin.package:
    name: "{{ lighttpd_package_name }}"
    state: present
    update_cache: true
