---
- name: Install EPEL repo (for RedHat)
  ansible.builtin.package:
    name: "{{ lighttpd_epel_package }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Lighttpd
  ansible.builtin.package:
    name: "{{ lighttpd_package_name }}"
    state: present
    update_cache: true
