---
- name: Checking operation system
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat', 'Suse']
    fail_msg: >-
      The {{ ansible_distribution }} (distribution  {{ ansible_os_family }})
      is not supported by this role.
    quiet: true

- name: Include variables for the current OS family
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install Lighttpd
  ansible.builtin.include_tasks: install.yml

- name: Configure Lighttpd
  ansible.builtin.include_tasks: configure.yml

- name: Manage Lighttpd service state
  ansible.builtin.include_tasks: service.yml
