- name: Управление состоянием и автозапуском службы
  ansible.builtin.service:
    name: "{{ lighttpd_service_name }}"
    state: "{{ lightt_service_state | default('started') }}"
    enabled: "{{ lighttpd_service_enabled | default(true) }}"