- name: Управление состоянием и автозапуском службы через systemd
  ansible.builtin.service:
    name: "{{ lighttpd_service_name }}"
    state: "{{ lighttpd_service_state }}"
    enabled: "{{ lighttpd_service_enabled }}"
  ignore_errors: true

- name: Принудительный запуск lighttpd для окружения Docker (без systemd)
  ansible.builtin.shell: |
    if ! pgrep -x "lighttpd" > /dev/null; then
      lighttpd -f {{ lighttpd_conf_path }}
    fi
  args:
    executable: /bin/bash
  changed_when: false
  when: ansible_virtualization_type in ['docker', 'podman', 'containerd'] or ansible_facts.services is not defined

- name: Показать лог ошибок lighttpd при сбое запуска
  ansible.builtin.shell: |
    if [ -f /var/log/lighttpd/error.log ]; then
      tail -n 20 /var/log/lighttpd/error.log
    else
      echo "Log file not found or empty"
    fi
  args:
    executable: /bin/bash
  register: error_log
  changed_when: false
  failed_when: false

- name: Вывод лога на экран
  ansible.builtin.debug:
    msg: "{{ error_log.stdout_lines }}"