---
- name: restart lighttpd
  ansible.builtin.service:
    name: "{{ lighttpd_service_name }}"
    state: restarted

- name: restart configuration lighttpd
  ansible.builtin.service:
    name: "{{ lighttpd_service_name }}"
    state: reloaded
