---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Проверка наличия и запуска службы lighttpd
      ansible.builtin.service:
        name: lighttpd
      register: service_status

    - name: Утверждение, что служба активна
      ansible.builtin.assert:
        that:
          - service_status.status.ActiveState == "active"
        fail_msg: "Служба lighttpd не запущена!"

    - name: Проверка открытия порта 80
      ansible.builtin.wait_for:
        port: 80
        host: 127.0.0.1
        timeout: 10

    - name: Отправка тестового HTTP-запроса к веб-серверу
      ansible.builtin.uri:
        url: "http://127.0.0.1:80/"
        method: GET
        status_code: [200, 403, 404]
      register: http_check

    - name: Утверждение, что HTTP-сервер ответил
      ansible.builtin.assert:
        that:
          - http_check.status in [200, 403, 404]
        fail_msg: "Lighttpd не вернул валидный HTTP-ответ"
